### ISSUE TITLE
Add motor controller code

### ISSUE THREAD

**Issue by va3wam** [va3wam/SegbotSTEP#4]
Replace the featherboard motor controller with one not controlled by I2C to speed up motor commands

**Comment by va3wam** [comment]
Doug has a "private" copy of the code in which the PID and motor control code is included and the robot is even balancing a bit.

**Comment by va3wam** [comment]
Being done in nerdoug/botcode for now. Will be ported to SegbotSTEP later

**Comment by nerdoug** [comment]
Thi works, and is in the nerdoug code that will soon be the SegbotSTEP master
